from modules.preprocessing.views import preprocess_text
from modules.language_detection.views import detect_language
from modules.aspect_extraction.views import extract_aspects
from modules.aspect_categorization.views import categorize_aspects